# Generated by Django 4.1.5 on 2023-01-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_stuck_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand_company",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="브랜드명"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="client_company",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="회사명"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="제품명"
            ),
        ),
    ]
