# Generated by Django 4.1.5 on 2023-01-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(verbose_name="가품발견수"),
        ),
    ]
