# Generated by Django 4.1.4 on 2023-01-18 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.CharField(default='', max_length=256, null=True, verbose_name='대표이미지')),
                ('category1', models.CharField(default='', max_length=256, null=True, verbose_name='카테고리1')),
                ('category2', models.CharField(default='', max_length=256, null=True, verbose_name='카테고리2')),
                ('nation', models.CharField(default='', max_length=256, null=True, verbose_name='국가')),
                ('channel', models.CharField(default='', max_length=256, null=True, verbose_name='유통채널')),
                ('product_price', models.CharField(default='', max_length=256, null=True, verbose_name='가격')),
                ('vendor_name', models.CharField(default='', max_length=256, null=True, verbose_name='판매상명')),
                ('crackdown', models.CharField(default='', max_length=256, null=True, verbose_name='단속근거')),
                ('prejudice1', models.CharField(default='', max_length=256, null=True, verbose_name='침해유형1')),
                ('prejudice2', models.CharField(default='', max_length=256, null=True, verbose_name='침해유형2')),
                ('report_date', models.CharField(default='', max_length=256, null=True, verbose_name='신고일자')),
                ('report_result', models.CharField(default='', max_length=256, null=True, verbose_name='신고결과')),
                ('url', models.CharField(default='', max_length=256, null=True, verbose_name='상품URL')),
                ('etc', models.CharField(default='', max_length=256, null=True, verbose_name='비고')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('status', models.CharField(choices=[('대기중', '대기중'), ('결제대기', '결제대기중'), ('결제완료', '결제완료'), ('환불', '환불')], default='대기중', max_length=32, verbose_name='상태')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
                'db_table': 'order',
            },
        ),
    ]
