# Generated by Django 4.1.5 on 2023-01-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_options"),
        ("order", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "프로젝트", "verbose_name_plural": "프로젝트"},
        ),
        migrations.AddField(
            model_name="order",
            name="category1",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="카테고리1"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="category2",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="카테고리2"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="channel",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="유통채널"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="crackdown",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="단속근거"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="etc",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="비고"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="main_img",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="대표이미지"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="nation",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="국가"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prejudice1",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="침해유형1"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prejudice2",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="침해유형2"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_price",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="가격"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="report_date",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="신고일자"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="report_result",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="신고결과"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="url",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="상품URL"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor_name",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="판매상명"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="상품명",
            ),
        ),
    ]
